# Site
repository: trangtoan293/trangtoan293.github.io

# Content configuration version
version: 2

# Personal info
name: Thanh-Toan TRANG
title: Data Engineer
email: trangtoan293@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: trangtoan293
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: thanh-toan-t-aa32651ba
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Having served as the Data Engineering Lead at Katalyst Vietnam JSC for a year, I've gained deep insights into data modelling and advanced data process development. My strong foundation in the finance sector is supported by Master's degree in European and International Private Banking from IAE Nice. This background enabled me to successfully design and implement an end-to-end DataVault Platform for one of Vietnam's premier banks, integrating the Data Vault Model and Data Transformation patterns on a Big Data Platform. I'm now eager to explore opportunities that will further develop my technical capabilities and allow me to work in an international environment, where I can harness new technologies to create innovative solutions.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Katalyst Vietnam Company
        link: katalyst.vn
        # link_text: boringcompany.com
        sub_title: Data Engineering Lead
        caption: Oct 2022 - Present

        description: |   
          ## Enterprise Data Modeling
          - Architected and implemented a cutting-edge enterprise data platform, leveraging Data Vault 2.0 modeling patterns to establish a robust and scalable data warehouse infrastructure. 
          - Developed an internal DataVault Automation Tool that accelerated modeling processes by 40% while minimizing manual errors.  
          ##  Data Pipeline Development
          - Orchestrated and engineered high-performance data workflows using Apache Airflow and Apache Spark, implementing version-controlled SQL transformations with dbt for comprehensive data lineage tracking
          - Implementing near real-time processing capabilities through micro-batch systems using Spark Structured Streaming.
          - Optimized Spark job configurations through sophisticated parameter tuning, achieving 40% reduction in execution time and 20% decrease in cluster resource utilization.   
          ## Infrastructure & Storage Management
          - Designed and implemented storage architecture utilizing MinIO services and Apache Iceberg for table format management, optimizing data storage through Parquet file format for enhanced query performance and compression efficiency.
          - Established strategic maintenance workflows for small-file handling, snapshot management, and metadata cleanup, improving query performance by 20%.  
          ## Data Catalog & Quality Assurance
          - Established comprehensive data catalog framework using DataHub for metadata management, data lineage tracking, and business glossary maintenance. 
          - Implemented robust data quality monitoring through Grafana, resulting in reduction in data-related incidents and enhanced data reliability.  
      
      - layout: left
        title: Home Credit Vietnam Financial Company
        link: homecredit.vn
        # link_text: boringcompany.com
        sub_title: Business Intelligence Lead
        caption: Dec 2019 - Oct 2022
        description: | # this will include new lines to allow paragraphs     
          ## Data Analytics & Business Intelligence
          - Enhancing financial reporting efficiency by implementing automated daily, monthly, and quarterly reporting systems, reducing manual processing time by 40% and saving approximately 60 hours monthly.
          - Led the development of enterprise-wide financial dashboards for the Board of Directors, consolidating cross-departmental data into strategic visualizations. Partnered with business units to automate customer lifetime value reporting, reducing generation time by 50% and enhancing strategic analysis capabilities.
          - Spearheaded the transformation of regulatory compliance reporting through advanced automation, ensuring 100% accuracy in SBV submissions while reducing preparation time by 50% and minimizing human errors.
          - Collaborated with finance and accounting teams to identify and automate key business processes, including payment reconciliation and month-end closing workflows, resulting in reducing processing time by 60%.  
          ## Technical Innovation & Process Optimization:
          - Engineered and deployed a robust data quality management framework utilizing Oracle, Apache Airflow, and VBA, implementing automated monitoring systems that proactively identify issues and alert stakeholders, resulting in a 40% reduction in data discrepancies.
          - Led the end-to-end automation of cross-system data reconciliation processes, seamlessly integrating with SAP Auto-booking workflows to achieve 70% improvement in processing accuracy and operational efficiency.
     
      - layout: left
        title: HC Collection Agency Company
        link: --
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: Jan 2021 - Present
        description: | # this will include new lines to allow paragraphs    
          ## Strategic Analytics Implementation
          - Architected and implemented end-to-end data infrastructure from scratch, leveraging Apache Airflow for workflow orchestration and dbt for data transformation. 
          - Established scalable data pipelines with PostgreSQL as the data warehouse, achieving 40% reduction in processing time.
          - Engineered comprehensive analytics dashboard through Metabase visualization platform, delivering the operator performance and payment dashboards
          - Implemented automated reporting systems that reduced manual effort by 50% while enhancing data accessibility for stakeholders.

      - layout: left
        title: Shinhan Bank Vietnam
        link: shinhan.com.vn
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: Jun 2017 - Nov 2019
        quote: >
          Data Analytics and Management Credit Assessment
        description: | # this will include new lines to allow paragraphs
          - Generate daily/monthly or ad-hoc management reports to managers and directors.
          - Closely track on resource and capacity planning.
          - Develop efficient scripting to manage data gathering, mining and transformation.
          - Monitor analytics and metrics results and delivering data-driven insight into emerging problems, trends as required.
          - Collaborate with Assessment/Draw-down/Collection departments to identify business process improvements.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left 
        caption: Sep 2014 - Sep 2016
        description: |
          #### Master of European and International Private Banking ####
          [IAE Nice - Université Côte d'Azur- FRANCE](https://univ-cotedazur.eu/)
      - layout: left
        caption: Sep 2011 - Sep 2014
        description: |
          #### Bachelor of Economics and Management ####
          [Toulouse 1 University Capitole - FRANCE](https://www.ut-capitole.fr/)
          

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left 
        caption: Apr 2024
        description: |
            [AWS Certified Cloud Practitioner](https://bit.ly/3vV8jpZ)
      - layout: left 
        caption: Mar 2023
        description: |
            [Data Vault 2.0 Practitioner](https://bit.ly/3UobAYa)

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs  
      - Programming Languages: Python
      - Big Data Technologies: Apache Spark, YARN, Apache Kafka, HDFS
      - Open Format Table: Apache Iceberg
      - Storage: MinIO
      - Streaming platform : Confluent
      - Database Management: Oracle, PostgreSQL, duckBD
      - Transformation tool: dbt
      - Orchestration: Apache Airflow
      - Version Control: Git
      - Data Modeling: Ralph Kimball, Data Vault 2.0
      - Team Collaboration and Communication

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
