# Site
repository: trangtoan293/trangtoan293.github.io

# Content configuration version
version: 2

# Personal info
name: Thanh-Toan TRANG
title: Data Engineer
email: trangtoan293@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: trangtoan293
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: thanh-toan-t-aa32651ba
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Having served as the Data Engineering Lead at Katalyst Vietnam JSC for a year, I've gained deep insights into data modelling and advanced data process development. My strong foundation in the finance sector is supported by Master's degree in European and International Private Banking from IAE Nice. This background enabled me to successfully design and implement an end-to-end DataVault Platform for one of Vietnam's premier banks, integrating the Data Vault Model and Data Transformation patterns on a Big Data Platform. I'm now eager to explore opportunities that will further develop my technical capabilities and allow me to work in an international environment, where I can harness new technologies to create innovative solutions.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Katalyst Vietnam Company
        link: katalyst.vn
        # link_text: boringcompany.com
        sub_title: Data Engineering Lead
        caption: Oct 2022 - Present
        quote: >
          Build Data Platform
        description: | 
            - Architect and implement a comprehensive modern data platform for the company.
            - Design Data Vault 2.0 modeling pattern to build a data warehouse.
            - Develop end-to-end data workflows on the data platform, including develop data pipeline, data catalog, data lineage, data quality and monitoring, resulting in an improvement in data reliability and more than 50% reduction in data-related incidents.
            - Design maintaining jobs, including small-files handling, snapshots expiring and removing old metadata files, optimizing query performance by 20%.
            - Optimize Spark jobs by fine-tuning configuration parameters, resulting in a 40% reduction in job execution time and a 20% decrease in cluster resource utilization.
            - Design and develop DataVault Automation Tool to accelerate the data modelling process by 40% and reducing manual errors.
      
      - layout: left
        title: Home Credit Vietnam Financial Company
        link: homecredit.vn
        # link_text: boringcompany.com
        sub_title: Business Intelligence Lead
        caption: Dec 2019 - Oct 2022
        quote: >
          Inhouse Data Platform
        description: | # this will include new lines to allow paragraphs
            - Report Automation: Spearheaded the generation of daily, monthly, and quarterly automated reports for the Finance Department.
            - Dashboard Maintenance: Diligently maintained and updated the Board of Directors' Finance dashboards, ensuring accuracy and relevancy.
            - Regulatory & Tax Reporting: Enhanced and automated regulatory and taxreporting processes, with meticulous data mapping and monitoring to guaranteeSBV reporting compliance.
            - Data Integrity & Alerts: Instituted data quality checks, along with early warning systems and alerts for critical issues.
            - Data Reconciliation & Automation: Automated reconciliations between diverse data sources and streamlined the integration with the SAP Auto-booking process.
            - IT Collaboration & Data Strategy: Partnered with IT to fine-tune data strategy,emphasizing the roles of DWH, DataMart, and Hadoop. Promoted the use of Hadoop for enhanced reporting, positioning it as a reliable backup solution.
            - Support for Transformation Initiatives: Actively supported company transformation projects, collaborating with the Accounting department to deliver essential regulatory components.
     
      - layout: left
        title: HC Collection Agency Company
        link: --
        # link_text: boringcompany.com
        sub_title: Data Engineer
        caption: Jan 2021 - Present
        quote: >
          Evaluate collection team performance
        description: | # this will include new lines to allow paragraphs
          - Building a small-scale data platform for a company
          - Process and integrate data using ETL processes to ensure accuracy and consistency by using dbt.
          - Design a data storage and visualization tool, such as Metabase, for creating an operator performance and Payment dashboard for the company.
          - Collect and analyze key performance metrics from collection team for reporting.
          - Enhance campaign approach to improve operator process.

      - layout: left
        title: Shinhan Bank Vietnam
        link: shinhan.com.vn
        # link_text: boringcompany.com
        sub_title: Data Analyst
        caption: Jun 2017 - Nov 2019
        quote: >
          Data Analytics and Management Credit Assessment
        description: | # this will include new lines to allow paragraphs
          - Generate daily/monthly or ad-hoc management reports to managers and directors.
          - Closely track on resource and capacity planning.
          - Develop efficient scripting to manage data gathering, mining and transformation.
          - Monitor analytics and metrics results and delivering data-driven insight into emerging problems, trends as required.
          - Collaborate with Assessment/Draw-down/Collection departments to identify business process improvements.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left 
        caption: Sep 2014 - Sep 2016
        description: |
          #### Master of European and International Private Banking ####
          [IAE Nice - Université Côte d'Azur- FRANCE](https://univ-cotedazur.eu/)
      - layout: left
        caption: Sep 2011 - Sep 2014
        description: |
          #### Bachelor of Economics and Management ####
          [Toulouse 1 University Capitole - FRANCE](https://www.ut-capitole.fr/)
          

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content: 
      - layout: left 
        caption: Apr 2024
        description: |
            [AWS Certified Cloud Practitioner](https://bit.ly/3vV8jpZ)
      - layout: left 
        caption: Mar 2023
        description: |
            [Data Vault 2.0 Practitioner](https://bit.ly/3UobAYa)

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **Programming Languages**: Python
      - Big Data Technologies: Apache Spark, YARN, Apache Kafka, HDFS
      - Open Format Table: Apache Iceberg
      - Storage: MinIO
      - Streaming platform : Confluent
      - Database Management: Oracle, PostgreSQL
      - Transformation tool: dbt
      - Orchestration: Apache Airflow
      - Version Control: Git
      - Data Modeling: Ralph Kimball, Data Vault 2.0
      - Team Collaboration and Communication

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
